Migrate test checks to buildenv

diff --git a/buildenv b/buildenv
--- a/buildenv
+++ b/buildenv
@@ -25,3 +25,26 @@ else
 	export ZOPEN_EXTRA_CFLAGS="-qnose -std=c11 -fgnu89-inline -I${ZOPEN_ROOT}/${ZOPEN_GIT_DIR}/lib,${ZOPEN_ROOT}/patches/PR1/include,/usr/include/le"
 	ln -s git-patches patches
 fi
+
+zopen_check_results()
+{
+# m4 check should have 4 (or 3) failures (3 if a git build)
+# Determine number of failures by looking at testcases on line _after_ 'Failed checks were:' line
+#
+dir="$1"
+pfx="$2"
+chk="$1/$2_check.log"
+
+set -x
+start_line=$(cat "${chk}" | egrep -n '^Failed checks were:' | awk -F':' '{ print $1 }')
+if [ $? -eq 0 ]; then
+	failures=$(cat "${chk}" | tail +${start_line} | head -2 | tail -1 | wc -w)
+	if [ ${failures} -gt 4 ]; then
+		exit 1
+	else
+		exit 0
+	fi
+fi
+exit 1
+}
+
